stages:
  - install
  - test
  - build
  - docker-fe
  - docker-be
  - deploy

image: node:22-slim

before_script:
  - apt-get update -y && apt-get install -y openssl
  - corepack enable
  - corepack prepare pnpm@latest --activate
  - pnpm config set store-dir .pnpm-store

cache:
  key:
    files:
      - be/pnpm-lock.yaml
      - fe/pnpm-lock.yaml
  paths:
    - be/node_modules/
    - fe/node_modules/

install:
  stage: install
  script:
    - pnpm --dir be install --frozen-lockfile --reporter=append-only
    - pnpm --dir fe install --frozen-lockfile --reporter=append-only

test:
  stage: test
  script:
    - pnpm --dir be install --frozen-lockfile --prefer-offline --reporter=append-only
    - pnpm --dir be run prisma:generate
    - pnpm --dir be run test

build:
  stage: build
  script:
    - pnpm --dir fe install --frozen-lockfile --prefer-offline --reporter=append-only
    - pnpm --dir be install --frozen-lockfile --prefer-offline --reporter=append-only
    - pnpm --dir be run prisma:generate
    - pnpm --dir fe run build
    - pnpm --dir be run build

docker-fe:
  stage: docker-fe
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - |
      cat > /kaniko/.docker/config.json <<EOF
      {
        "auths": {
          "ghcr.io": {
            "username": "$GHCR_USERNAME",
            "password": "$GHCR_TOKEN"
          }
        }
      }
      EOF
  script:
    - echo $GHCR_FE_IMAGE
    - |
      /kaniko/executor --context ./fe --dockerfile ./fe/Dockerfile --destination $GHCR_FE_IMAGE
  only:
    - main

docker-be:
  stage: docker-be
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - |
      cat > /kaniko/.docker/config.json <<EOF
      {
        "auths": {
          "ghcr.io": {
            "username": "$GHCR_USERNAME",
            "password": "$GHCR_TOKEN"
          }
        }
      }
      EOF
  script:
    - |
      /kaniko/executor --context ./be --dockerfile ./be/Dockerfile --destination $GHCR_BE_IMAGE
  only:
    - main=$GHCR_FE_IMAGE,push=true
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - scp -o StrictHostKeyChecking=no $FE_ENV_FILE $SERVER_USER@$SERVER_IP:~/asset-management-monorepo/fe/.env
    - scp -o StrictHostKeyChecking=no $ENV_FILE $SERVER_USER@$SERVER_IP:~/asset-management-monorepo/be/.env
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "GHCR_USERNAME=$GHCR_USERNAME GHCR_TOKEN=$GHCR_TOKEN GHCR_FE_IMAGE=$GHCR_FE_IMAGE GHCR_BE_IMAGE=$GHCR_BE_IMAGE bash ~/deploy.sh"
  only:
    - main
