stages:
  - install
  - test
  - build
  - docker-build-frontend
  - docker-build-backend
  - prisma
  - push-fe
  - push-be
  - deploy

image: node:22-slim

before_script:
  - apt-get update -y && apt-get install -y openssl
  - corepack enable
  - corepack prepare pnpm@latest --activate
  - pnpm config set store-dir .pnpm-store

cache:
  key:
    files:
      - be/pnpm-lock.yaml
      - fe/pnpm-lock.yaml
  paths:
    - be/node_modules/
    - fe/node_modules/

install:
  stage: install
  script:
    - pnpm --dir be install --frozen-lockfile --reporter=append-only
    - pnpm --dir fe install --frozen-lockfile --reporter=append-only

test:
  stage: test
  script:
    - pnpm --dir be install --frozen-lockfile --prefer-offline --reporter=append-only
    - pnpm --dir be run prisma:generate
    - pnpm --dir be run test

build:
  stage: build
  script:
    - pnpm --dir fe install --frozen-lockfile --prefer-offline --reporter=append-only
    - pnpm --dir be install --frozen-lockfile --prefer-offline --reporter=append-only
    - pnpm --dir fe run build
    - pnpm --dir be run build

# docker-build-frontend:
#   image: docker:24
#   stage: docker-build-frontend
#   before_script: []
#   services:
#     - name: docker:24-dind
#       alias: docker
#   variables:
#     DOCKER_HOST: tcp://docker:2375
#     DOCKER_TLS_CERTDIR: ""
#   script:
#     - docker info
#     - docker build -t asset-management-frontend:latest ./fe

# docker-build-backend:
#   image: docker:24
#   stage: docker-build-backend
#   before_script: []
#   services:
#     - name: docker:24-dind
#       alias: docker
#   variables:
#     DOCKER_HOST: tcp://docker:2375
#     DOCKER_TLS_CERTDIR: ""
#   script:
#     - docker build -t asset-management-backend:latest ./be

prisma:
  stage: prisma
  script:
    - pnpm --dir be install --frozen-lockfile --prefer-offline --reporter=append-only
    - pnpm --dir be run prisma:migrate
  only:
    - main

push-fe:
  image: docker:latest
  stage: push-fe
  before_script: []
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Pushing frontend Docker image to registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag asset-management-frontend:latest $CI_REGISTRY_IMAGE/frontend:latest
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
  only:
    - main

push-be:
  image: docker:latest
  stage: push-be
  before_script: []
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Pushing backend Docker image to registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag asset-management-backend:latest $CI_REGISTRY_IMAGE/backend:latest
    - docker push $CI_REGISTRY_IMAGE/backend:latest
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - scp -o StrictHostKeyChecking=no $FE_ENV_FILE $SERVER_USER@$SERVER_IP:~/asset-management-monorepo/fe/.env
    - scp -o StrictHostKeyChecking=no $ENV_FILE $SERVER_USER@$SERVER_IP:~/asset-management-monorepo/be/.env
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "CI_REGISTRY=$CI_REGISTRY CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE CI_REGISTRY_USER=$CI_REGISTRY_USER CI_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD bash ~/deploy.sh"
  only:
    - main
