export enum BorrowStatus {
  PENDING = 'PENDING',
  PROVIDED = 'PROVIDED',
  APPROVED = 'APPROVED',
  OVERDUE = 'OVERDUE',
  CANCELED = 'CANCELED',
  REJECTED = 'REJECTED',
  RETURNED = 'RETURNED',
}
